% Expert System rules generated from cluster summaries

cluster(6, [feature(brands, 'SAMSUNG'), feature(models, 'X3 SuperZoom '), feature(colors, 'Black'), feature(memory, '8'), feature(storage, '128'), feature(camera, 'True'), feature(rating, '4.30'), feature(sellingprice, '16999.00'), feature(originalprice, '29999.00'), feature(mobile, 'realme X3 SuperZoom '), feature(discount, '0.00'), feature(discountpercentage, '0.00'), feature(os, 'Android'), feature(sellersamount, '420'), feature(screensize, '5.70'), feature(batterysize, '3558'), feature(reviews, '48')]).
cluster(0, [feature(brands, 'SAMSUNG'), feature(models, 'iPhone XR '), feature(colors, 'Black'), feature(memory, '4'), feature(storage, '64'), feature(camera, 'True'), feature(rating, '4.30'), feature(sellingprice, '9999.00'), feature(originalprice, '9999.00'), feature(mobile, 'Apple iPhone XR '), feature(discount, '0.00'), feature(discountpercentage, '0.00'), feature(os, 'Android'), feature(sellersamount, '319'), feature(screensize, '4.60'), feature(batterysize, '4177'), feature(reviews, '11')]).
cluster(7, [feature(brands, 'SAMSUNG'), feature(models, 'Zenfone Selfie '), feature(colors, 'Black'), feature(memory, '4'), feature(storage, '64'), feature(camera, 'True'), feature(rating, '4.30'), feature(sellingprice, '9999.00'), feature(originalprice, '9999.00'), feature(mobile, 'ASUS Zenfone Selfie '), feature(discount, '0.00'), feature(discountpercentage, '0.00'), feature(os, 'Android'), feature(sellersamount, '482'), feature(screensize, '6.40'), feature(batterysize, '5916'), feature(reviews, '78')]).
cluster(1, [feature(brands, 'SAMSUNG'), feature(models, 'iPhone 11 '), feature(colors, 'Black'), feature(memory, '4'), feature(storage, '64'), feature(camera, 'True'), feature(rating, '4.30'), feature(sellingprice, '9999.00'), feature(originalprice, '11999.00'), feature(mobile, 'Apple iPhone 11 '), feature(discount, '0.00'), feature(discountpercentage, '0.00'), feature(os, 'Android'), feature(sellersamount, '998'), feature(screensize, '6.50'), feature(batterysize, '3809'), feature(reviews, '706')]).
cluster(3, [feature(brands, 'Apple'), feature(models, 'iPhone 13 Pro Max '), feature(colors, 'Black'), feature(memory, '6'), feature(storage, '128'), feature(camera, 'True'), feature(rating, '0.00'), feature(sellingprice, '6499.00'), feature(originalprice, '6499.00'), feature(mobile, 'Apple iPhone 13 Pro Max '), feature(discount, '0.00'), feature(discountpercentage, '0.00'), feature(os, 'Android'), feature(sellersamount, '266'), feature(screensize, '5.30'), feature(batterysize, '5761'), feature(reviews, '27')]).
cluster(2, [feature(brands, 'SAMSUNG'), feature(models, 'iPhone 11 '), feature(colors, 'Black'), feature(memory, '4'), feature(storage, '64'), feature(camera, 'True'), feature(rating, '4.30'), feature(sellingprice, '9999.00'), feature(originalprice, '10999.00'), feature(mobile, 'Apple iPhone 11 '), feature(discount, '0.00'), feature(discountpercentage, '0.00'), feature(os, 'Android'), feature(sellersamount, '134'), feature(screensize, '6.80'), feature(batterysize, '2679'), feature(reviews, '8')]).
cluster(5, [feature(brands, 'SAMSUNG'), feature(models, 'iPhone 6s '), feature(colors, 'Black'), feature(memory, '4'), feature(storage, '64'), feature(camera, 'True'), feature(rating, '4.30'), feature(sellingprice, '9999.00'), feature(originalprice, '9999.00'), feature(mobile, 'Apple iPhone 6s '), feature(discount, '0.00'), feature(discountpercentage, '0.00'), feature(os, 'Android'), feature(sellersamount, '585'), feature(screensize, '4.70'), feature(batterysize, '2336'), feature(reviews, '374')]).
cluster(8, [feature(brands, 'Apple'), feature(models, 'iPhone 13 Pro Max'), feature(colors, 'Silver'), feature(memory, '4'), feature(storage, '256'), feature(camera, 'True'), feature(rating, '4.60'), feature(sellingprice, '64900.00'), feature(originalprice, '64900.00'), feature(mobile, 'Apple iPhone 13 Pro Max'), feature(discount, '0.00'), feature(discountpercentage, '0.00'), feature(os, 'IOS'), feature(sellersamount, '5'), feature(screensize, '5.60'), feature(batterysize, '5284'), feature(reviews, '229')]).
cluster(4, [feature(brands, 'SAMSUNG'), feature(models, 'F11 Pro'), feature(colors, 'Black'), feature(memory, '4'), feature(storage, '64'), feature(camera, 'True'), feature(rating, '4.30'), feature(sellingprice, '10990.00'), feature(originalprice, '14990.00'), feature(mobile, 'OPPO F11 Pro'), feature(discount, '4000.00'), feature(discountpercentage, '26.67'), feature(os, 'Android'), feature(sellersamount, '563'), feature(screensize, '6.20'), feature(batterysize, '3623'), feature(reviews, '246')]).
